language: scala
addons:
  apt:
    update: true
sudo: required
before_install:
- curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
- wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376edfd8e4b08b35f174935bf97bbac/sbt && chmod +x ./sbt
script:
- ./sbt run test
- ./target/scala-2.11/scalaprops-native-example-out
- ./target/scala-2.11/scalaprops-native-example-test-out
jdk:
- openjdk8
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
